site_name: Spline Architect Plugin Documentation
repo_url: https://www.fab.com/listings/356b1d13-5080-4418-893d-5a39546bc276
docs_dir: docs/

theme:
  name: material
  features:
    - content.images.lightbox

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Spline Architect Plugin Documentation (EN)"
        - locale: lt
          name: Lietuvių
          build: true
          site_name: "Spline Architect Plugin'o Dokumentacija (LT)"
  - glightbox:
markdown_extensions:
  - markdown.extensions.extra
  - markdown.extensions.attr_list
  - md_in_html
  - attr_list
  - admonition
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-YV8FLGPN35